cbus_config:
  canid: 1
  consumer: true
  events:
    0000000A:
      variables: FF85
  major_code_version: 0
  manufacturer_id: 165
  minor_code_version: 1
  mode: 1
  module_id: 72
  name: 'PIRFID '
  node_number: 258
  node_variables: 0xFF,0xFF,0xFF,0xDD,0xEE,0xFF,0x00,0x00,0x00,0x00,0x00
  number_events: 40
  number_of_node_variables: 10
  number_of_parameters: 20
  producer: true
  variables_per_event: 2
node_config:
  cangrid_host: pi
  cangrid_port: 4444
  log_file: node.log
  log_level: DEBUG
  service_port: 7777
rfids:
  976876: 4
  964238131: 300
  16014023131: 1234
